name: PartitelleBotTest

on:
  pull_request:
    branches:
      - main
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy-partitellebot-test') }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PartitelleBotTest
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_TEST_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TEST_API_KEY }}
