name: PartitelleBot + PartitelleBotTest

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PartitelleBot
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
      - name: Deploy to PartitelleBotTest
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_TEST_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TEST_API_KEY }}
