name: PartitelleBotTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'deploy-partitellebot-test') }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PartitelleBotTest
        uses: johnbeynon/render-deploy-action@747373cdb7b9b3f561438e063ee0815b71584f1b
        with:
          service-id: ${{ secrets.RENDER_TEST_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TEST_API_KEY }}
          wait-for-success: true
